# Generated by Django 5.2.16 on 2026-07-08 15:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('body', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'received_webhooks',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('recipient', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'Sms'), ('push', 'Push')], max_length=10)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('priority', models.SmallIntegerField(default=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('dead_letter', 'Dead Letter'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('send_at', models.DateTimeField()),
                ('next_attempt_at', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=5)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, max_length=255, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('lock_expires_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jobs',
                'indexes': [models.Index(condition=models.Q(('status', 'pending')), fields=['-priority', 'next_attempt_at'], name='idx_jobs_claimable'), models.Index(condition=models.Q(('status', 'processing')), fields=['lock_expires_at'], name='idx_jobs_stale_lock'), models.Index(condition=models.Q(('status', 'sent')), fields=['recipient', 'sent_at'], name='idx_jobs_recipient_sent'), models.Index(fields=['status'], name='idx_jobs_status')],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_status', models.CharField(max_length=30)),
                ('url', models.URLField(max_length=2048)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField()),
                ('error', models.TextField(blank=True, null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_deliveries', to='jobs.job')),
            ],
            options={
                'db_table': 'webhook_deliveries',
            },
        ),
        migrations.CreateModel(
            name='JobEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=30)),
                ('worker_id', models.CharField(blank=True, max_length=255, null=True)),
                ('detail', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='jobs.job')),
            ],
            options={
                'db_table': 'job_events',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['job', 'created_at'], name='idx_job_events_job_id')],
            },
        ),
    ]
